
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    user:
      name: paas
      password: paas
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect