
server:
  servlet:
    context-path: /paas
spring:
  datasource:
    username: yugabyte
    url: jdbc:postgresql://20.119.92.177:5433/yugabyte
    password: Hackathon22!
    connection-test-query: SELECT 1
    testWhileIdle: true
    test-on-borrow: true
    hikari:
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 90000
      connectionTimeout: 60000
      connectionTestQuery: SELECT 1
      maxLifetime: 1200000
      leak-detection-threshold: 2000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
      show_sql: true
jwt:
  secret: secret

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: false
    #path: /swagger-ui.html

azure:
  subscriptionKey: 5630cf56b90e481a809a97a7a7acc535
  subscriptionRegion: eastus
  languages-list: https://westus.tts.speech.microsoft.com/cognitiveservices/voices/list