
server:
  servlet:
    context-path: /paas
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: pass7799
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
      show_sql: true
jwt:
  secret: secret

azure:
  subscriptionKey: 592ccaa9c6254922a4f3b45b2b4c6c65
  subscriptionRegion: eastus
  languages-list: https://westus.tts.speech.microsoft.com/cognitiveservices/voices/list