
server:
  servlet:
    context-path: /paas
spring:
  datasource:
    username: yugabyte
    url: jdbc:postgresql://20.119.92.177:5433/yugabyte
    password: Hackathon22!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
jwt:
  secret: secret