
server:
  servlet:
    context-path: /paas
spring:
  datasource:
    username: yugabyte
    url: jdbc:postgresql://20.119.92.177:5433/yugabyte
    password: Hackathon22!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
      show_sql: true
jwt:
  secret: secret


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

azure:
  subscriptionKey: 5630cf56b90e481a809a97a7a7acc535
  subscriptionRegion: eastus
  languages-list: https://westus.tts.speech.microsoft.com/cognitiveservices/voices/list