spring:
  datasource:
    username: ashwin
    url: jdbc:postgresql://localhost:5432/passdb
    password: ash123
#  security:
#    user:
#      name: paas
#      password: paas
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update